version: '3'

volumes:
    postgres_data: {}
    postgres_backup: {}
    staticfiles: {}
    static_dir: {}

services:
  server:
    container_name: prod_andela_social_server
    env_file:
      - ./prod.env
    build:
      context: ../../server
      dockerfile: ../docker/server/Dockerfile
    depends_on:
      - database
      - client
    ports:
      - "8000:8000"
    volumes:
      - static_dir:/andela_social/static
      - staticfiles:/andela_social/staticfiles
      
  client:
    container_name: prod_andela_social_client
    build:
      context: ../../client
      dockerfile: ../docker/prod/client/Dockerfile
    env_file:
      - ./prod.env
    ports:
      - "9000:9000"
    volumes:
      - /andela_social/node_modules/

  database:
    container_name: prod_andela_socials_db
    build:
      context: ../../docker/database
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - "8093:5432"
  
  nginx:
    container_name: nginx_server
    build: ../nginx
    depends_on:
      - server
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
